import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, UserButton } from "@clerk/nextjs";
import { dark } from '@clerk/themes'
import { ThemeProvider } from "@/components/theme-provider";

import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Toaster } from "sonner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Strimo",
  description: "Generated by Dev Raj Dev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <ClerkProvider >
    <html lang="en" >
      <body>
       
         <ThemeProvider
            attribute="class"
             forcedTheme="dark"
            storageKey="strimo-theme"
          >
          {/* <h1>hii</h1> */}
          
          {/* <Link href="/sign-in"><Button variant="outline">Sign In</Button></Link> */}
          <Toaster theme="light" position="bottom-center" />  
            {children}
          </ThemeProvider>
      </body>
    </html>
      </ClerkProvider>
  );
}
